HotelWebsite/Controllers/HomeController.cs
using System.Web.Mvc;

namespace HotelWebsite.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        // Landing Page
        public ActionResult Index()
        {
            return View();
        }
      
        //Interior with Aside and Header Image
        public ActionResult Interior()
        {
            return View();
        }

        //Interior with Aside and No Header Image
        public ActionResult InteriorNoHeader() 
        {
            return View();
        }
        
        //Interior One Column and Header Image
        public ActionResult InteriorOneColumn() 
        {
            return View();
        }

        //Interior One Column and No Header Image
        public ActionResult InteriorOneColNoHeader()
        {
            return View();
        }
    }
}

HotelWebsite/Controllers/MediaController.cs
using System.Collections.Generic;
using DevTrends.MvcDonutCaching;
using System;
using System.Linq;
using System.Web.Mvc;
using HotelWebsite.Models.Media;

namespace HotelWebsite.Controllers
{
    public class MediaController : Controller
    {
        [DonutOutputCache(CacheProfile = "StandardCache")]
        public ActionResult Index()
        {
            var model = MarcusApps.Api.PhotoGallery.GetAlbums();

            return View(model);
        }

        public ActionResult Video()
        {
            return View();
        }

        [DonutOutputCache(CacheProfile = "StandardCache")]
        public ActionResult Album(Guid id, Guid? photo)
        {
            var photos = MarcusApps.Api.PhotoGallery.GetAlbumPhotos(id);

            var photoModels = photos as IList<PhotoModel> ?? photos.ToList();

            if (photos != null && photoModels.Any())
            {
                var firstOrDefault = photoModels.FirstOrDefault();
                if (firstOrDefault != null)
                {
                    var model = firstOrDefault.Album;

                    model.Photos = photoModels;
                    model.StartingIndex = 0;
                    model.StartingIndex = photoModels.ToList().FindIndex(x => x.Id == photo);
                    
                    if (model.StartingIndex < 0) model.StartingIndex = 0;

                    return View(model);
                }
            }
            return View();
        }

        [DonutOutputCache(CacheProfile = "StandardCache")]
        public PartialViewResult AlbumWidget(string album)
        {
            var albums = MarcusApps.Api.PhotoGallery.GetAlbums(true).Where(x=>x.Name.ToLower() == album.ToLower());

            var albumModels = albums as IList<AlbumModel> ?? albums.ToList();

            if (albumModels.Any())
            {                
                var model = albumModels.FirstOrDefault();
                if (model != null)
                {
                    model.Photos = MarcusApps.Api.PhotoGallery.GetAlbumPhotos(model.Id);
                    return PartialView(model);
                }
            }
            return PartialView();
        }
    }
}

HotelWebsite/Controllers/PackagesController.cs
using DevTrends.MvcDonutCaching;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using HotelWebsite.Models.Packages;

namespace HotelWebsite.Controllers
{
    public class PackagesController : Controller
    {
        [DonutOutputCache(CacheProfile = "StandardCache")]
        public ActionResult Index()
        {
            return View();
        }

        [DonutOutputCache(CacheProfile = "StandardCache")]
        public ActionResult Details(Guid id)
        {
            var package = MarcusApps.Api.Packages.Get(id) ?? new PackageModel();

            return View(package);
        }

        [DonutOutputCache(CacheProfile = "StandardCache")]
        public PartialViewResult Banner(string categoryName)
        {
            var packages = MarcusApps.Api.Packages.GetByCategoryName(categoryName);
            
            return PartialView(packages);
        }

        public PartialViewResult Listing()
        {
            var model = new PackageListingModel
            {
                Categories = new List<CategoryModel>(),
                Packages = new List<PackageModel>()
            };

            var packages = MarcusApps.Api.Packages.GetAll().Where(x => !x.IsHidden);
            var packageModels = packages as PackageModel[] ?? packages.ToArray();

            model.Packages = packageModels;

            var categories = new List<CategoryModel>();

            foreach (var package in packageModels.Where(package => package.Categories.Any()))
            {
                categories.AddRange(package.Categories.Where(x => !x.IsDisabled));
            }

            model.Categories = categories.Distinct().OrderBy(x => x.Name);


            return PartialView("_Listing", model);
        }

    }
}

HotelWebsite/Views/Shared/templates/Home.cshtml
<!-- Full Page Slider -->
@if (Request.QueryString["mode"] != "edit"){
    @Html.Action("AlbumWidget", "Media", new { album = "homepage" })
}
<!-- Mobile Utility Navigation-->
@Html.Partial("_Mobile-Utility-Nav")

<div id="content-main" data-cms-zone="contentMain"></div>

@Html.Action("Banner", "Packages", new { categoryName = "homepage" })

<div id="content-bottom" data-cms-zone="contentBottom"></div>
<!-- Location Section / Contact Section -->
@Html.Partial("_Location-Social-Connect")
       
@section scripts
{
    <!-- Full Page Main Slider for use on the Homepage -->
    <script type="text/javascript">
        
        /***** Initialize Full-page Slider ********/
        (function () {
            var $example = $('#fs-slider'),
            $frame = $('.frame', $example);
            //$caption = $('#caption', $example),
            //$count = $('#count', $example);
            $frame.mightySlider({
                //load: getHeight(),
                autoScale: 1,
                speed: 1000,
                moveBy: 300,
                viewport: 'fill',
                preloadMode: 'nearby',
                easing: 'easeOutExpo',
                // Scrolling Options
                scrolling: {
                    scrollBy: 0
                },
                //Cycling Options
                cycling: { 
                    cycleBy: 'slides',
                    pauseTime: 5000,
                    pauseOnHover: 1
                },
                // Navigation options
                navigation: {
                    slideSize: '100%',
                    keyboardNavBy: 'slides'
                },

                // Deep-linking options
                //deeplinking: {
                //    linkID: 'main-page-slider'
                //},

                // Dragging
                dragging: {
                    swingSpeed: 0.1
                },

                // Commands
                commands: {
                    buttons: 1
                }
            },
            {
                active: function (name, index) {
                    //$caption.html(this.slides[index].options.caption);
                    //$count.html((index + 1) + '/' + this.slides.length + '&nbsp;&nbsp;&nbsp;&nbsp;' + this.slides[index].options.name);
                }
            });
        })();
    </script>
}

HotelWebsite/Views/Shared/templates/Interior.cshtml
<!-- Interior Template with Header Image and Secondary-Navigation-->

<div id="content-header" data-cms-zone="contentHeader"></div>

<!-- Mobile Utility Navigation-->
@Html.Partial("_Mobile-Utility-Nav")

<!-- Content Section -->

<!-- Two Column with Aside -->
<section class="two-column__content content1020__wrapper">
    @Html.Partial("_Breadcrumbs")
    <div class="main-col">
        <!-- Widget could go here but typically Title with Text, Should we lock this down-->
        <div id="content-main" data-cms-zone="contentMain" data-cms-forceResize="true"></div>
    </div>
    <aside class="aside-nav aside__nav--large">
        @Html.Partial("_Secondary-Nav")
    </aside>
</section>

<!-- Widget Section -->
<div id="content-bottom" data-cms-zone="contentBottom"></div>
<!-- End Widget Section -->
<!-- End Content Section-->
<aside class="aside-nav aside-nav aside__nav--medium">
    @Html.Partial("_Secondary-Nav")
</aside>

HotelWebsite/Views/Shared/templates/InteriorActivities.cshtml
<!-- Interior Template with Header Image and Secondary-Navigation-->

<div id="content-header" data-cms-zone="contentHeader"></div>

<!-- Mobile Utility Navigation-->
@Html.Partial("_Mobile-Utility-Nav")

<!-- Content Section -->
<!-- Two Column with Aside Button for Activities Page Only -->
<section class="two-column__content content1020__wrapper">
    @Html.Partial("_Breadcrumbs")
    <div class="main-col">
        <!-- Widget could go here but typically Title with Text, Should we lock this down-->
        <div id="content-main" data-cms-zone="contentMain" data-cms-forceresize="true"></div>
    </div>
    <!-- This was added to take the place of the side navigation for the Activities Page-->
    <aside class="aside-nav aside__nav--large">
        <a href="/wisconsin-weekend-getaway/resort-activities" class="btn btn--color1">Back to All</a>
    </aside>
</section>

<!-- Widget Section -->
<div id="content-bottom" data-cms-zone="contentBottom"></div>
<!-- End Widget Section -->
<!-- End Content Section-->

HotelWebsite/Views/Shared/templates/InteriorNoHeader.cshtml
<!-- Interior Template with No Header but secondary navigation -->

<!-- Content Section -->

<!-- Two Column with Aside -->
<section class="two-column__content content1020__wrapper no-header">
    @Html.Partial("_Breadcrumbs")
    <div class="main-col">
       <!-- Widget could go here but typically Title with Text, Should we lock this down-->
        <div id="content-main" data-cms-zone="contentMain"></div>
    </div>
    <aside class="aside-nav">
        @Html.Partial("_Secondary-Nav")
    </aside>
</section>

<!-- This is a Widget Zone -->
<div id="content-bottom" data-cms-zone="contentBottom"></div>

<!-- End Widget Zone -->

<!-- End Content Section-->

HotelWebsite/Views/Shared/templates/InteriorOneColNoHeader.cshtml
<!-- Interior One Column with No Header Image -->

<!-- Mobile Utility Navigation-->
@Html.Partial("_Mobile-Utility-Nav")

<!-- Content -->
<section class="content1020__wrapper one-column__content">
    @Html.Partial("_Breadcrumbs")
    <!--Content can go here Typically Title with Copy-->
    <div id="content-main" data-cms-zone="contentMain"></div>
</section>

<!-- Widget Zone -->
<div id="content-bottom" data-cms-zone="contentBottom"></div>

<!-- End Widget Zone -->

<!-- End Content -->

HotelWebsite/Views/Shared/templates/InteriorOneColumn.cshtml
<!--Interior Template with no secondary navigation-->

<div id="content-header" data-cms-zone="contentHeader"></div>

<!-- Mobile Utility Navigation-->
@Html.Partial("_Mobile-Utility-Nav")

<!-- Content -->
<section class="content1020__wrapper one-column__content">
    @Html.Partial("_Breadcrumbs")
    <!--Content can go here Typically Title with Copy-->
   <div id="content-main" data-cms-zone="contentMain"></div>
</section>

<!-- Widget Zone -->   
<div id="content-bottom" data-cms-zone="contentBottom"></div>

<!-- End Widget Zone -->
<!-- End Content -->