HotelWebsite/Controllers/ContactController.cs
using System;
using System.Web.Mvc;
using System.Data.SqlClient;
using HotelWebsite.Models.Forms;

namespace HotelWebsite.Controllers
{
    public class ContactController : Controller
    {
        private const string ConnString = "Data Source=mhs-mssql1-aws; Initial Catalog=Web01; Uid=web01user; Pwd=m@rcu$@pp$; MultipleActiveResultSets=true";

        public ActionResult EmailSignUp()
        {
            var model = new ContactModel
                {
                    EmailAddress = Request["emailAddress"]
                };
            return View(model);
        }

        [HttpPost]
        public ActionResult EmailSignUp(ContactModel model)
        {
            SignUpByLid(00, model);

            //if (model.Spa) SignUpByLid(59,model);
            //if (model.Dining) SignUpByLID(13,model);
            //if (model.Holidays) SignUpByLID(15,model);

            return RedirectToAction("EmailSignUpSuccess");
        }

        public void SignUpByLid(int lid, ContactModel model) {

            using (var conn = new SqlConnection(ConnString))
            {
                conn.Open();

                var cmd = new SqlCommand(String.Format("exec sp_EML_SignUps '{0}', '{1}'", lid, model.EmailAddress), conn);
                var reader = cmd.ExecuteReader();

                if (!reader.HasRows)
                {

                    var cmdInsert = new SqlCommand(String.Format("exec sp_EML_InsertEmailSignUp '{0}', '{1}', '{2}','{3}','{4}','{5}','{6}','{7}','{8}','{9}','{10}','{11}','{12}','{13}','{14}','{15}'",
                        lid,
                        "BaseHotel",
                        model.FirstName,
                        model.LastName,
                        model.EmailAddress,
                        model.Address1,
                        model.Address2,
                        model.City,
                        model.State,
                        model.ZipCode,
                        model.BirthdayMonth,
                        model.BirthdayDay,
                        model.AnniversaryMonth,
                        model.AnniversaryDay,
                        model.Comments,
                        ""
                        ), conn);

                    cmdInsert.ExecuteNonQuery();
                }
            }
        }

        public ActionResult EmailSignUpSuccess()
        {
            return View();
        }

        [HttpPost]
        public ActionResult EmailUnsubscribe(string EmailAddress)
        {
            UnsubscribeByLid(00, EmailAddress);

            return RedirectToAction("EmailUnsubscribeSuccess");
        }

        public void UnsubscribeByLid(int lid, string email)
        {

            using (var conn = new SqlConnection(ConnString))
            {
                conn.Open();

                var cmd = new SqlCommand(String.Format("exec sp_EML_SunsubscribeEmail '{0}', '{1}'",
                    lid,
                    email
                    ), conn);

                cmd.ExecuteNonQuery();
            }
        }
        public ActionResult ContactUs()
        {
            var model = new ContactModel(); 
            return View(model);

        }

        public ActionResult ContactUsSuccess()
        {
            return View();
        }
    }
}

HotelWebsite/Views/Contact/ContactUs.cshtml
@model HotelWebsite.Models.Forms.ContactModel
@{
    ViewBag.Title = "Contact Heidel House Resort and Spa | Green Lake, Wisconsin ";
    ViewBag.SeoPageDescription = "Contact Heidel House Resort and Spa for Wisconsin lakeside getaway resort reservations, spa and salon appointments and restaurant reservations.";
}

<div class="content1020__wrapper one-column__content no-header">
    <h1 class="section__header">Contact Us</h1>

    <div class="section__text">
        <p>
            Please contact Heidel House Resort & Spa with any questions, comments or concerns you may have. It is our pleasure to assist you. We are available by phone 24 hours a day or you can reach us by email, mail, fax or through our online chat.  
        </p>
        <p>
            Don’t forget to connect with us on <a href="https://www.facebook.com/heidelhouse" target="_blank">Facebook</a> and <a href="https://twitter.com/HeidelHouse" target="_blank">Twitter</a>! Additionally, we welcome you to <a href="/contact/contactus">subscribe</a> to our e-newsletter for the latest special offers and upcoming events.
        </p>
        <p>
            Local: 920.294.3344 <br/>
            Toll Free: 800.444.2812 <br/>
            Fax: 920.294.6128 <br/>
        </p>
        <br/>    
        <p>643 Illinois Avenue<br/>Green Lake, WI 54941</p>
        <p>Local: 920.294.3344</p>
        <p>Toll Free: 800.444.2812</p>
        <p>Fax: 920.294.6128</p>
    </div>

    <section class="form__section">

    <form id="contactus" enctype="multipart/form-data" class="rfp__form" method="post" action="http://api.marcusapps.com/forms/submissions/post">
        <input type="hidden" name="formKey" value="heidelhouse-contact" />
        <input type="hidden" name="redirectUrl" value="http://www.heidelhouse.com/contact/contactussuccess" />
        <br/>
                <div class="columns">
                    <div class="c3x6">
                        @Html.LabelFor(model => Model.FirstName, "First Name:*", new { @class = "form__label" })
                        @Html.TextBoxFor(model => Model.FirstName, new { @class = "form__input", type = "text", placeholder = "First Name*", required = "required" })
                        @Html.LabelFor(model => Model.LastName, "Last Name:*", new { @class = "form__label" })
                        @Html.TextBoxFor(model => Model.LastName, new { @class = "form__input", type = "text", placeholder = "Last Name*", required = "required" })
                       
                        @Html.LabelFor(model => Model.PhoneNumber, "Phone:", new { @class = "form__label" })
                        @Html.TextBoxFor(model => Model.PhoneNumber, new { @class = "form__input", type = "tel", placeholder = "xxx-xxx-xxxx" })
                        @Html.LabelFor(model => Model.Address1, "Address:", new { @class = "form__label" })
                        @Html.TextBoxFor(model => Model.Address1, new { @class = "form__input", type = "text", placeholder = "Address" })
                        @Html.LabelFor(model => Model.City, "City:", new { @class = "form__label" })
                        @Html.TextBoxFor(model => Model.City, new { @class = "form__input", type = "text", placeholder = "City" })
                        @Html.LabelFor(model => Model.State, "State", new { @class = "form__label" })
                        @Html.DropDownListFor(model => model.SelectedStates, Model.AvailableStates, new { @class = "form__select" })
                        @Html.LabelFor(model => Model.ZipCode, "Zip:", new { @class = "form__label" })
                        @Html.TextBoxFor(model => Model.ZipCode, new { @class = "form__input", type = "number", placeholder = "Zip Code" })

                    </div>
                    <div class="c3x6">
                        @Html.LabelFor(model => Model.EmailAddress, "Email:*", new { @class = "form__label" })
                        @Html.TextBoxFor(model => Model.EmailAddress, new { @class = "form__input", type = "email", placeholder = "email@example.com*", required = "required" })
                        @Html.LabelFor(model => Model.ContactReason, "Nature of Request:*", new { @class = "form__label" })
                        @Html.DropDownListFor(model => model.SelectedReasons, Model.ContactReason, new { @class = "form__select", required="required" })
                        @Html.LabelFor(model => Model.Comments, "Comments:*", new { @class = "form__label" })
                        @Html.TextAreaFor(model => Model.Comments, new { @class = "form__textarea", placeholder = "Comments", required="required"})

                        <input id="formSubmit" type="submit" onclick="ga('send', 'event', 'submit', 'click', 'contact us');" class="btn btn--color1 btn--formsubmit" value="Submit" />
                    </div>
                </div>
        <br/>
    </form>

    </section>

</div>

HotelWebsite/Views/Contact/ContactUsSuccess.cshtml
@model HotelWebsite.Models.Forms.ContactModel
@{
    ViewBag.Title = "Contact Heidel House Resort and Spa | Green Lake, Wisconsin ";
    ViewBag.SeoPageDescription = "Contact Heidel House Resort and Spa for Wisconsin lakeside getaway resort reservations, spa and salon appointments and restaurant reservations.";
}

<div class="content1020__wrapper one-column__content no-header">
    <h1 class="section__header">Contact Us</h1>

    <div class="section__text">
        <p>Thank you for your submission. We're be in contact shortly.</p>
    </div>
</div>

HotelWebsite/Views/Contact/EmailSignUp.cshtml
@model HotelWebsite.Models.Forms.ContactModel

@{
    ViewBag.Title = "Email Subscribe | Hotel Property | Location, State";
    ViewBag.SeoPageDescription = "Email subscribe description for seo.";
}

<div class="content1020__wrapper one-column__content no-header">
    <h1 class="section__header">Subscribe</h1>

    <div class="section__text">
        <p>Subscribe to our free e-mail newsletter.</p>
        <p>Lorem ipsum</p>
    </div>

    <section class="form__section">
        @using (Html.BeginForm("EmailSignUp", "Contact", FormMethod.Post, new { enctype = "multipart/form-data", @id = "EmailSignUpForm", @class = "email-signup__form" }))
        {
            @Html.ValidationSummary(true)
            <div class="columns">
                <div class="c3x6">
                    @Html.LabelFor(model => Model.FirstName, "First Name:*", new { @class = "form__label" })
                    @Html.TextBoxFor(model => Model.FirstName, new { @class = "form__input", type = "text", tabindex = "1", placeholder = "First Name", required = "required" })
                    @Html.LabelFor(model => Model.LastName, "Last Name:*", new { @class = "form__label" })
                    @Html.TextBoxFor(model => Model.LastName, new { @class = "form__input", type = "text", tabindex = "2", placeholder = "Last Name", required = "required" })
                    @Html.LabelFor(model => Model.EmailAddress, "Email:*", new { @class = "form__label" })
                    <input name="EmailAddress" class="form__input" type="email" required data-parsley-trigger="change" tabindex="3" placeholder="email@email.com" />
                    @Html.LabelFor(model => Model.ZipCode, "Zip:*", new { @class = "form__label" })
                    <input name="ZipCode" class="zipcode form__input" type="number" tabindex="4" value="" maxlength="5" pattern="\d*" placeholder="Zip Code" required>

                </div>
                <div class="c3x6">

                    @Html.LabelFor(model => Model.BirthdayMonth, "Birthday Month:", new { @class = "form__label" })
                    <input class="form__input" data-parsley-trigger="change" id="BirthdayMonthID" data-parsley-type="integer" data-parsley-min="1" data-parsley-max="12" name="BirthdayMonth" pattern="\d*" placeholder="Month" tabindex="5" data-error-message="Must be a number." />

                    @Html.LabelFor(model => Model.BirthdayDay, "Birthday Day:", new { @class = "form__label" })
                    <input class="form__input" data-parsley-trigger="change" data-parsley-type="integer" data-parsley-min="1" data-parsley-max="31" pattern="\d*" placeholder="Day" name="BirthdayDay" tabindex="6">

                    @Html.LabelFor(model => Model.AnniversaryMonth, "Anniversary Month:", new { @class = "form__label" })
                    <input class="form__input" data-parsley-trigger="change" id="AnniversaryMonthId" data-parsley-type="integer" data-parsley-min="1" data-parsley-max="12" name="AnniversaryMonth" pattern="\d*" placeholder="Month" tabindex="7" data-error-message="Must be a number." />

                    @Html.LabelFor(model => Model.AnniversaryDay, "Anniversary Day:", new { @class = "form__label" })
                    <input class="form__input" data-parsley-trigger="change" data-parsley-type="integer" data-parsley-min="1" data-parsley-max="31" pattern="\d*" placeholder="Day" name="AnniversaryDay" tabindex="8">

                    <input type="submit" class="btn btn--color1 btn--formsubmit" tabindex="12" onclick="ga('send', 'event', 'submit', 'click', 'email us');" value="Submit" />
                </div>
            </div>
        }
    </section>
    <section class="form__section email-unsubscribe">
        <h1 class="section__header">Unsubscribe</h1>
        <div class="email-unsubscribe__container">
            <div class="section__text">
                <p>Enter your email address here to unsubscribe from the Pfister email list.<p>
            </div>
            @using (Html.BeginForm("EmailUnsubscribe", "Contact", FormMethod.Post, new { enctype = "multipart/form-data", @id = "EmailUnsubscribeForm", @class = "email-signup__form email-signup__form--unsubscribe" }))
            {
                @Html.ValidationSummary(true)
                <div class="columns">
                    @Html.LabelFor(model => Model.EmailAddress, "Email:*", new { @class = "form__label" })
                    <input name="EmailAddress" class="form__input" type="email" tabindex="13" required data-parsley-trigger="change" placeholder="email@email.com" />
                    <input type="submit" class="btn btn--color1 btn--formsubmit" onclick="ga(['send', 'event', 'submit', 'click', 'email-unsubscribe']);" value="Unsubscribe" />
                </div>
            }
        </div>
    </section>
</div>

@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#EmailSignUpForm').parsley();
            $('#EmailUnsubscribeForm').parsley();
        });

    </script>
}

HotelWebsite/Views/Contact/EmailSignUpSuccess.cshtml
@model HotelWebsite.Models.Forms.ContactModel

@{
    ViewBag.Title = "Email Subscribe | Heidel House Resort and Spa | Green Lake, Wisconsin";
    ViewBag.SeoPageDescription = "Receive exclusive Wisconsin resort specials from Heidel House Resort and Spa in your email inbox. Signup for package, restaurant, salon and spa deals.";
}

<div class="content1020__wrapper one-column__content no-header">
    <h1 class="section__header">Email Signup</h1>

    <div class="section__text">
        <p>Thanks! You've successfully been signed up to receive Heidel House emails.</p>
    </div>
</div>

HotelWebsite/Views/Contact/EmailUnsubscribeSuccess.cshtml
@{
    ViewBag.Title = "Email Un-Subscribe | Base Hotel | location, state";
    ViewBag.SeoPageDescription = "Email Unsubscribe";
}

<div class="content1020__wrapper one-column__content no-header">
    <h1 class="section__header">Email Unsubscribe</h1>

    <div class="section__text">
        <p>We're sad to see you go. Feel free to resubscribe when you're ready, or check out our social media platforms!</p>
    </div>
</div>