HotelWebsite/Controllers/MenuController.cs
using DevTrends.MvcDonutCaching;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using HotelWebsite.Models.Pages;

namespace HotelWebsite.Controllers
{
    public class MenuController : Controller
    {
        [DonutOutputCache(CacheProfile = "StandardCache")]
        public ActionResult Main()
        {
            var items = MarcusApps.Api.Pages.GetTreeMenu("/", 3);

            return PartialView(items);
        }

        [DonutOutputCache(CacheProfile = "StandardCache")]
        public ActionResult Breadcrumbs(string breadcrumbPageId = "", string page = "")
        {
            if (!String.IsNullOrEmpty(breadcrumbPageId))
            {
                var id = new Guid(breadcrumbPageId);
                var items = MarcusApps.Api.Pages.GetBreadcrumbsByPageId(id);
                return PartialView(items);
            }
            
            // see if we can get breadcrumbs based on controllers/action
            try
            {
                var rd = ControllerContext.ParentActionViewContext.RouteData;                   
                var currentController = rd.GetRequiredString("controller");

                var items = new List<PageModel>
                    {
                        new PageModel {PageName = "Home", FriendlyUrl = "/"},
                        new PageModel {PageName = currentController, FriendlyUrl = "/" + currentController}
                    };

                return PartialView(items);
            }
            catch
            {

            }

            return Content("");
        }

        [DonutOutputCache(CacheProfile = "StandardCache")]
        public ActionResult SideNav(string sideNavPageId = "")
        {
            if (!String.IsNullOrEmpty(sideNavPageId))
            {
                var topLevelParent = MarcusApps.Api.Pages.GetTopLevelParentByChildPageId(new Guid(sideNavPageId));

                var items = topLevelParent.ParentPageId == null
                                 ? MarcusApps.Api.Pages.GetTreeMenu(new Guid(sideNavPageId), 2).ToList()
                                 : MarcusApps.Api.Pages.GetTreeMenu(topLevelParent.Id, 2).ToList();

                ViewBag.PageId = sideNavPageId;

                return PartialView(items);
            }

            return Content("");
        }
    }
}

HotelWebsite/Views/Shared/Package-Banner.cshtml
<section class="fp-image__section">
    <div id="fw-slider" class="mightyslider_paper_skin">
        <div class="frame">
            <div class="slide_element">
                <div class="slide" data-mightyslider="cover: 'https://placehold.it/1700x445', name:'<a href=&quot;#&quot; class=&quot;btn btn--color1&quot;>Click Here</a>', ID: 'cherry-blossoms', caption: 'Lorem ipsum dolor sit amet '"></div>
                <div class="slide" data-mightyslider="cover: 'https://mightyslider.com/assets/img/photos/Bicycle-Macro-Bokeh-1080x1920.jpg', name:'Bicycle Macro Bokeh', ID: 'bicycle', caption: 'Lorem ipsum dolor sit amet'"></div>
                <div class="slide" data-mightyslider="cover: 'https://mightyslider.com/assets/img/photos/girl.jpg', name:'Little girl', ID: 'little-girl', caption: 'Lorem ipsum dolor sit amet. And Other Stuff'"></div>
                <div class="slide" data-mightyslider="cover: 'https://mightyslider.com/assets/img/photos/334513-1920x1080.jpg', name:'Love', ID: 'love', caption: 'Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo.'"></div>
                <div class="slide" data-mightyslider="cover: 'https://mightyslider.com/assets/img/photos/joy-wallpaper-1920x1080.jpg', name:'Joy', ID: 'joy', caption: 'Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.'"></div>
            </div>
            <div class="details">
                <div id="caption2">
                    &nbsp;
                </div>
                <div id="callout-button">

                </div>
            </div>
        </div>
    </div>
</section>

HotelWebsite/Views/Shared/Three-Column-Feature.cshtml
<section class="featured__section content1020__wrapper">
    <ul class="featured__list">
        <li class="featured__item">
            <a href="#" class="featured__link">
                <figure class="featured__figure">
                    <img src="https://ipsumimage.appspot.com/630x400" alt="Featured Accomodation" class="crop1" />
                    <img src="https://ipsumimage.appspot.com/370x370" alt="Featured Accomodation" class="crop2" />
                    <figcaption class="featured__caption">
                        Elegant Accommodations
                    </figcaption>
                </figure>
            </a>
            <div class="featured__content">
                <h2 class="featured__header">Elegant Accommodations</h2>
                <p class="featured__text">
                    Enjoy superior accommodations featuring magnificent furnishings, round-the-clock personal service and wireless, high-speed Internet access. Take a deep breath and relax knowing our facility is smoke-free.  On the 23rd floor overlooking Lake Michigan, Blu is Milwaukee’s most sophisticated martini and wine bar with awe-inspiring views.
                </p>
                <a href="#" class="btn btn--color1 btn--more">Read More</a>
            </div>
        </li>
        <li class="featured__item">
            <a href="#" class="featured__link">
                <figure class="featured__figure">
                    <img src="https://ipsumimage.appspot.com/630x400" alt="Featured Accomodation" class="crop1" />
                    <img src="https://ipsumimage.appspot.com/370x370" alt="Featured Accomodation" class="crop2" />
                    <figcaption class="featured__caption">
                        Memorable Events
                    </figcaption>
                </figure>
            </a>
            <div class="featured__content">
                <h2 class="featured__header">Memorable Events</h2>
                <p class="featured__text">
                    Known for fabulous galas and elegant weddings, The Pfister® will make your event sparkle. Plan a meeting or special event in our function space, showcasing captivating ballrooms, intimate boardrooms, and every detail the discerning traveler could request. With a reputation for perfection, The Pfister promises to make your event unforgettable.
                </p>
                <a href="#" class="btn btn--color1 btn--more">Read More</a>
            </div>
        </li>
        <li class="featured__item">
            <a href="#" class="featured__link">
                <figure class="featured__figure">
                    <img src="https://ipsumimage.appspot.com/630x400" alt="Featured Accomodation" class="crop1" />
                    <img src="https://ipsumimage.appspot.com/370x370" alt="Featured Accomodation" class="crop2" />
                    <figcaption class="featured__caption">
                        <span>In the Heart of Downtonw Milwaukee</span>
                    </figcaption>
                </figure>
            </a>
            <div class="featured__content">
                <h2 class="featured__header">In the Heart of Downtown Milwaukee</h2>
                <p class="featured__text">
                    Three blocks from the shores of Lake Michigan, The Pfister® Hotel overlooks downtown Milwaukee’s east side and is moments from exciting attractions including the Milwaukee Art Museum and the Summerfest grounds, which host an unparalleled calendar of events. Museums, theater, shopping, nightlife and much more are within walking distance.
                </p>
                <a href="#" class="btn btn--color1 btn--more">Read More</a>
            </div>
        </li>
    </ul>
</section>

HotelWebsite/Views/Shared/_Breadcrumbs.cshtml
<div class="breadcrumb-social__section">
    @Html.Action("Breadcrumbs", "Menu", new { breadcrumbPageId = ViewBag.PageId })

    <!-- Go to www.addthis.com/dashboard to customize your tools -->
    <!--<div class="addthis_sharing_toolbox"></div>-->
    <div class="social-sharing">
        <span class="social-sharing__text">Share This:</span>
        <a class="addthis_button_facebook">
            <figure class="social-sharing__icon">
                <img src="~/img/social-icons/facebook.svg" alt="Facebook Icon" />
            </figure>
        </a>
        <a class="addthis_button_twitter">
            <figure class="social-sharing__icon">
                <img src="~/img/social-icons/twitter.svg" alt="twitter icon" />
            </figure>
        </a>
        <a class="addthis_button_pinterest_share">
            <figure class="social-sharing__icon">
                <img src="~/img/social-icons/pinterest.svg" alt="Pinterest Share Icon" />
            </figure>
        </a>
        <a class="addthis_button_google_plusone_share">
            <figure class="social-sharing__icon">
                <img src="~/img/social-icons/googleplus.svg" alt="Google+ Share Icon" />
            </figure>
        </a>
        <a class="addthis_button_email">
            <figure class="social-sharing__icon">
                <img src="~/img/social-icons/email.svg" alt="Email Share Icon" />
            </figure>
        </a>
    </div>
    <!-- Go to www.addthis.com/dashboard to customize your tools -->
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-54471d34799b80f0"></script>

</div>

HotelWebsite/Views/Shared/_Desktop-Utility-Nav.cshtml
<div class="utility-nav__wrapper">
    <div class="utility-nav--desktop">
        <div class="ut-nav__list">
            <div class="ut-nav__item ut-nav--email">
                <a href="~/contact/emailsignup" onclick="ga('send', 'event', 'utility nav', 'click', 'email');" class="ut-nav__link">Email Sign Up</a>
            </div>
            <div class="ut-nav__item ut-nav--contact">
                <a href="~/contact/contactus" onclick="ga('send', 'event', 'utility nav', 'click', 'contact us');" class="ut-nav__link">Contact Us</a>
            </div>
            <div class="ut-nav__item ut-nav--search">
                <a href="javascript:void(0)" onclick="ga('send', 'event', 'utility nav', 'click', 'search');" class="ut-nav__link">Search</a>

                <form action="~/Search/" id="searchForm">
                    <input type="hidden" name="cx" value="009413127227991692106:0ilehyn4fi8" />
                    <input type="hidden" name="ie" value="UTF-8" />
                    <div class="no-show search-box">
                        <input class="search" name="q" style="width:120px; display:inline-block;" type="text" placeholder="Search" id="searchInput" />
                        <input type="submit" style="width:90px; display:inline-block;" value="search" id="send2" class="btn btn--color1 btn--search" />
                    </div>
                </form>
            
            </div>
            <div class="ut-nav__item ut-nav--phone">
                <a href="tel:800-444-2812" class="phone-number ut-nav__link"><span class="phone-number">800.444.2812</span></a>
            </div>
        </div>
    </div>
</div>

HotelWebsite/Views/Shared/_Footer.cshtml
<!-- Footer -->
<footer class="footer">
    <div class="footer-top">
        <div class="content1020__wrapper--footer">
            <div class="columns">
                <div class="c2x6">
                    <div class="site-map">
                        <h3 class="footer__header">More</h3>
                        <ul class="site-map__list">
                            <li class="site-map__item">
                                <a href="/hospitality-careers" class="site-map__link">Employment</a>
                            </li>
                            <li class="site-map__item">
                                <a href="/contact/contactus" class="site-map__link">Contact</a>
                            </li>
                            <li class="site-map__item">
                                <a href="/terms-conditions" class="site-map__link">Terms of Use</a>
                            </li>
                            <li class="site-map__item">
                                <a href="/privacy-policy" class="site-map__link">Privacy Policy</a>
                            </li>
                            <li class="site-map__item">
                                <a href="https://res.travlynx.com/bbe/page2.aspx?pcode=HCHHRC&checkin=&nights=1&adults=1&children=0" class="site-map__link">Reservations</a>
                            </li>
                            <li class="site-map__item">
                                <a href="/contact/emailsignup" class="site-map__link">Email Signup</a>
                            </li>
                        </ul>
                        <ul class="site-map__list">
                            <li class="site-map__item">
                                <a href="http://blog.heidelhouse.com" target="_blank" class="site-map__link">Blog</a>
                            </li>
                            <li class="site-map__item">
                                <a href="http://www.marcushotels.com/hotel-management-portfolio/hotel-management-portfolio.asp" target="_blank" class="site-map__link">Marcus Portfolio</a>
                            </li>
                            <li class="site-map__item">
                                <a href="http://press.marcushotels.com/?s=heidel" class="site-map__link">Newsroom</a>
                            </li>
                            <li class="site-map__item">
                                <a href="/pages/sitemap" class="site-map__link">Sitemap</a>
                            </li>
                            <li class="site-map__item">
                                <a href="http://store.heidelhouse.com/" target="_blank" class="site-map__link">Gift Certificates</a>
                            </li>
                            <li class="site-map__item">
                                <a href="/heidel-house-information" class="site-map__link">FAQs</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="c2x6">
                    <div class="connect">
                        <h3 class="footer__header">Connect</h3>
                        <div class="social">
                            <ul class="social-icon__list">
                                <li class="social-icon__item"><a href="https://www.facebook.com/heidelhouse" target="_blank" class="social__link"><div class="social-icon__block"><img src="~/img/social-icons/facebook.svg" alt="Facebook Icon" /></div><span class="visuallyhidden">Facebook</span></a></li>
                                <li class="social-icon__item"><a href="http://www.twitter.com/heidelhouse" target="_blank" class="social__link"><div class="social-icon__block"><img src="~/img/social-icons/twitter.svg" alt="twitter icon" /></div><span class="visuallyhidden">Twitter</span></a></li>
                                <li class="social-icon__item"><a href="http://www.pinterest.com/heidelhouse/" target="_blank" class="social__link"><div class="social-icon__block"><img src="~/img/social-icons/pinterest.svg" alt="Pinterest Icon" /></div><span class="visuallyhidden">Pinterest</span></a></li>
                                <li class="social-icon__item"><a href="https://plus.google.com/u/0/107795782655602956250/posts" target="_blank" class="social__link"><div class="social-icon__block"><img src="~/img/social-icons/googleplus.svg" alt="Google Plus Icon" /></div><span class="visuallyhidden">GooglePlus</span></a></li>
                                <li class="social-icon__item"><a href="https://www.youtube.com/user/HeidelHouseResort" target="_blank" class="social__link"><div class="social-icon__block"><img src="~/img/social-icons/youtube.svg" alt="YouTube Icon" /></div><span class="visuallyhidden">YouTube</span></a></li>
                                <li class="social-icon__item"><a href="http://instagram.com/heidelhouse" target="_blank" class="social__link"><div class="social-icon__block"><img src="~/img/social-icons/instagram.svg" alt="Instagram" /></div><span class="visuallyhidden">Blog</span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="c2x6">
                    <div class="contact">
                        <h3 class="footer__header">Contact</h3>
                        <address class="footer__address">
                            <p>Heidel House Resort &amp; Spa</p>
                            <p>643 Illinois Ave.</p>
                            <p>Green Lake, WI 54941</p>
                        </address>
                        <div class="footer__phone">
                            <p><a class="phone__link" href="tel:800-444.2812">800.444.2812</a></p>
                            <p><a class="email__link" href="emailto:info@heidelhouse.com">info@heidelhouse.com</a></p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="footer-bottom">
        <div class="copyright">
            &copy;2014 The Marcus Corporation. All Rights Reserved.
        </div>
    </div>
</footer>

HotelWebsite/Views/Shared/_Full-Page-Slider.cshtml
<section class="full-slider--wrapper">
    <div class="main-slideshow">
        <div id="fs-slider" class="mightyslider_windows8_skin">
            <div class="frame" data-mightyslider="width:1500, height:500">
                <div class="slide_element">
                    <!-- This mark-up is preferred for image loading purposes but I don't think it will work with the CMS structure-->
                    <div class="slide" data-mightyslider="cover: [
                         [' /img/homepage-slider-example.png'],
                    ['/img/homepage-slider-example.png','(min-width:800px)'],
                    ['/img/homepage-slider-example.png', '(min-width:1200px)']
                    ],
                    caption: '<span class=&quot;slider__header&quot;>Historic</span><span class=&quot;slider__header--sub&quot;>Tradition</span>' ">
                </div>
                <div class="slide" data-mightyslider="cover: [
                     [' /img/homepage-slider-example.png'],
                ['/img/homepage-slider-example.png','(min-width:800px)'],
                ['/img/homepage-slider-example.png', '(min-width:1200px)']
                ],
                caption: '<span class=&quot;slider__header&quot;>Grand</span><span class=&quot;slider__header--sub&quot;>Elegance</span>'">
            </div>
                </div>
            </div>
            <div class="details">
                <div id="caption">
                    &nbsp;
                </div>
            </div>
        </div>
    </div>
</section>

HotelWebsite/Views/Shared/_Interior-Header-Slider.cshtml
<!-- Specific to Interior Pages -->
<!-- Header Slider... keep in case they want the top to be a slider -->
<!-- Currently Not Used-->

<section class="full-slider--wrapper">
    <div class="interior-slideshow">
        <div id="interior-slider" class="mightyslider_windows8_skin">
            <div class="frame">
                <div class="slide_element">
                    <div class="slide" data-mightyslider="cover: 'https://ipsumimage.appspot.com/1080x1920', name:'Cherry blossoms by the bench', ID: 'cherry-blossoms', caption: '<span class=&quot;slider__header&quot;>Lorem ipsum</span> <span class=&quot;slider__header--sub&quot;>dolor sit amet</span>, <a href=&quot;http://ilightbox.net&quot; target=&quot;_blank&quot;>consectetuer adipiscing elit</a>.'"></div>
                    <div class="slide" data-mightyslider="cover: 'https://ipsumimage.appspot.com/1920x1080', name:'Bicycle Macro Bokeh', ID: 'bicycle', caption: 'Aenean commodo ligula eget dolor. Aenean massa.'"></div>
                    <div class="slide" data-mightyslider="cover: 'https://ipsumimage.appspot.com/1080x1920', name:'Little girl', ID: 'little-girl', caption: 'You can link to this slide by adding <b>#fullscreen/little-girl</b> to url.<br><a href=&quot;fullscreen.html#fullscreen/little-girl&quot; target=&quot;_blank&quot;>Create new tab</a>'"></div>
                    <div class="slide" data-mightyslider="cover: 'https://ipsumimage.appspot.com/1920x1080', name:'Love', ID: 'love', caption: 'Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo.'"></div>
                    <div class="slide" data-mightyslider="cover: 'https://ipsumimage.appspot.com/1080x1920', name:'Joy', ID: 'joy', caption: 'Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.'"></div>
                </div>
            </div>
            <div class="details">
                <div id="caption">
                    &nbsp;
                </div>
            </div>
        </div>
    </div>
</section>

HotelWebsite/Views/Shared/_Intro-Copy.cshtml
<section class="landing-intro__bkgrd">
    <div class="landing-intro__section content1020__wrapper">
        <div class="fancy-intro">
            <h2 class="landing-intro__subheader">an oasis of</h2>
            <h1 class="landing-intro__header">RELAXATION</h1>
        </div>
        <div class="intro__section">
            <p class="intro__text">
                The Pfister<sup>&reg;</sup> Hotel, built in 1893 has been the premier downtown Milwaukee hotel for over a century, and continues to celebrate a tradition of gracious service and impeccable style. From the moment you arrive, you'll notice the extraordinary architecture, and a welcoming ambiance marked by a priceless Victorian art collection which rivals that of any hotel in the world.
            </p>
        </div>
    </div>
</section>

HotelWebsite/Views/Shared/_Mobile-Utility-Nav.cshtml
@{
    ViewBag.Title = "_Mobile-Utility-Nav";
}

<!-- Mobile Utility Navigation -->
<section class="secondary-nav--mobile">
    <div class="content1020__wrapper">
        <div class="email-us">
            <figure class="secondary-nav__figure">
                <a class="" href="/contact/contactus">
                    <img src="/img/icons/contact-us.png" alt="Phone Icon" />
                </a>
            </figure>
        </div>
        <div class="location">
            <figure class="secondary-nav__figure">
                <a href="/wisconsin-resort/green-lake-resort">
                    <img src="/img/icons/location-icon.png" alt="Location Icon" />
                </a>
            </figure>
        </div>
        <div class="contact-us">
            <figure class="secondary-nav__figure">
                <a href="/media">
                    <img src="/img/icons/gallery-icon.png" alt="Photo Gallery Icon" />
                </a>
            </figure>
        </div>
    </div>
    <!--<div>Call Us NOW!!!!</div>-->
</section>

HotelWebsite/Views/Shared/_Primary-Nav.cshtml
<header id="header2" class="header">
    <!--<section class="content1020__wrapper content1020__wrapper--header">-->
        <div class="mobile-nav">

            <a class="nav-btn" id="nav-open-btn" href="#nav">
                <figure class="mobile-nav__figure icon__mobile">
                    <img src="~/img/icons/menu-icon.png" id="open-menu-image" alt="Mobile Menu" />
                    <img src="~/img/icons/close-icon.png" id="close-menu-image" class="no-show" alt="Mobile Menu" />
                </figure>
            </a>

        </div>

        <div class="branding">
            <a href="/">
                <figure class="branding__figure">
                    <img class="branding__image" src="~/img/heidel-house-logo.jpg" alt="Heidel House Resort" />
                </figure>
            </a>
        </div>

        <div class="book-now">
            <a href="https://res.travlynx.com/bbe/page2.aspx?pcode=HCHHRC&LanguageID=1&Rooms=1&PackageID=none&BookingURL=&checkin=10%2F27%2F2014&nights=1&adults=2&children=0" target="_blank">
                <figure class="book-now__figure icon__mobile">
                    <img src="/img/icons/booknow-icon.png" alt="Book Now" />
                </figure>
            </a>
        </div>

        <!-- Desktop Utility Nav -->
        @Html.Partial("_Desktop-Utility-Nav")
        <nav id="nav" class="nav__wrapper" role="navigation">
            <a class="close-btn" id="nav-close-btn" href="#top"><img src="~/img/icons/close-icon.png" /></a>

            @Html.Action("Main", "Menu")

        </nav>
        
        <div class="reserve">
            <div>
                <a class=" btn btn--color2 btn--reservation" onclick="ga('send', 'event', 'primary nav', 'click', 'reservation dropdown');" href="javascript:void(0)">
                    Reserve Now
                </a>
            </div>
        </div>
        <div id="resForm" class="reservation">
            <!-- Populate the values for HotelID and LanguageID below. -->
            <form action="https://res.travlynx.com/bbe/page2.aspx?pcode=HCHHRC&checkin=&nights=1&adults=1&children=0" method="get" name="resform" id="resform" class="reservation__form">
                <input type="hidden" name="pcode" value="HCHHRC">
                <input type="hidden" name="LanguageID" value="1">
                <input type="hidden" name="Rooms" value="1">
                <input type="hidden" name="PackageID" value="none">
                <input type="hidden" name="BookingURL" value="">


                <div class="columns reservation__section">
                    <div id="datePicker-Res"></div>
                    <div class="c3x6 flt-right">
                        <div class="reservation__field">
                            <label class="reservation__label">Check In </label>
                            <input name="checkin" type="text" id="PickupDate" class="reservation__input reservation__input--date" value="">
                        </div>
                        <div class="reservation__field">
                            <label class="reservation__label">Nights:</label>
                            <select name="nights" class="reservation__select--nights">
                                <option value="1" selected="selected">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="7">7</option>
                                <option value="8">8</option>
                                <option value="9">9</option>
                                <option value="10">10</option>
                                <option value="10">11</option>
                                <option value="10">12</option>
                                <option value="10">13</option>
                                <option value="10">14</option>
                            </select>
                        </div>
                        <div class="reservation__field">
                            <label class="reservation__label">Adults:</label>
                            <select name="adults" class="reservation__select--adults">
                                <option value="1">1</option>
                                <option value="2" selected="selected">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                            </select>
                        </div>
                        <div class="reservation__field">
                            <label class="reservation__label">Children:</label>
                            <select name="children" class="reservation__select--children">
                                <option value="0" selected="selected">0</option>
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                            </select>
                        </div>

                        <input type="submit" value="Book Now" class="btn btn--color1 btn--reserve" formtarget="_blank" onclick="ga('send', 'event', 'primary nav', 'click', 'book reservation'); postIHForm(document.resform); return false;" />
                    </div>
                </div>

            </form>
        </div><!-- End Div for drop down reservation -->
    <!--</section>-->
</header>

HotelWebsite/Views/Shared/_Product-Banner.cshtml
<section class="banner__section">
    <div class="banner__wrapper columns">
        <div class="banner-image c2x6">
            <figure class="banner__figure">
                <img src="https://ipsumimage.appspot.com/180x230" alt="Banner Image" />
            </figure>
        </div>
        <div class="banner-text c4x6">
            <h3 class="banner__header">Banner Callout Text </h3>
            <p class="banner__text">I am text that will make you want to buy the product/hotel/thingy that is deemed buyable.</p>
            <div class="banner-button">
                <a href="" class="btn btn--color2 btn--banner">Buy Now</a>
            </div>
        </div>
    </div>
</section>

HotelWebsite/Views/Shared/_Secondary-Nav.cshtml
@Html.Action("SideNav", "Menu", new { sideNavPageId = ViewBag.PageId })

HotelWebsite/Views/Shared/_TitleWithCopy.cshtml
<div class="fancy-intro">
    <div class="title__section">
        <h2 class="tag-line__header">World Class</h2>
        <h1 class="title-line__header">Accommodations</h1>
    </div>
</div>
<div class="interior-editor">
    <p>
        The vision of businessman Guido Pfister and his son Charles, the Pfister opened in 1893 as a “Grand Hotel of the West” and a welcoming and luxurious meeting place.  It surely succeeded on both fronts. It was the most lavish hotel of its time, constructed at a cost of over $1 million, with groundbreaking features such as fireproofing, electricity throughout the hotel and thermostat controls in every room.
    </p>
    <p>
        Showing it's age, The Pfister was purchased in 1962 by Ben Marcus, who vowed to renovate the distinguished hotel to its original beauty.  Significant renovations were completed and a new 23-story guest room tower added. An extensive art collection continues to grace the walls of The Pfister today .
    </p>
</div>